apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: my-first-pipeline-
spec:
  arguments:
    parameters: []
  entrypoint: my-first-pipeline
  serviceAccountName: pipeline-runner
  templates:
  - container:
      args:
      - echo "hello world"
      command:
      - sh
      - -c
      image: library/bash:4.4.23
    name: echo
    outputs:
      artifacts:
      - name: mlpipeline-ui-metadata
        optional: true
        path: /mlpipeline-ui-metadata.json
      - name: mlpipeline-metrics
        optional: true
        path: /mlpipeline-metrics.json
  - dag:
      tasks:
      - name: echo
        template: echo
      - dependencies:
        - echo
        name: uname
        template: uname
    name: my-first-pipeline
  - container:
      args:
      - uname
      command:
      - sh
      - -c
      image: library/bash:4.4.23
    name: uname
    outputs:
      artifacts:
      - name: mlpipeline-ui-metadata
        optional: true
        path: /mlpipeline-ui-metadata.json
      - name: mlpipeline-metrics
        optional: true
        path: /mlpipeline-metrics.json
